default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['POSTGRES_NAME'] %>
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: postgres

development:
  <<: *default

test:
  <<: *default

production:
<<: *default